### ISSUE TITLE
R package installation error

### ISSUE THREAD

**Issue by rrusso81** [carl-mc/pspm#1]
Trying to install this package on a Linux machine and getting the following error, any help would be appreciated.

* installing *source* package ‘pspm’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘pspm’:
 .onLoad failed in loadNamespace() for 'pspm', details:
  call: NULL
  error: ImportError: cannot import name 'OrderedDict'

Error: loading failed
Execution halted

**Comment by carl-mc** [comment]
OrderedDict is a function in the python3 standard module [typing](https://docs.python.org/3/library/typing.html) which the package depends upon. Is reticulate in R drawing on python3 (call reticulate::py_config() in R)? If not, [change reticulate's configuration accordingly](https://rstudio.github.io/reticulate/articles/versions.html). Otherwise, you may need to call reticulate::py_install(c("typing")). Does this help?

**Comment by rrusso-81** [comment]
Yes thank you!

**Comment by rrusso81** [comment]
Yes, thank you!

**Comment by rrusso81** [comment]
Hello, 
Sorry but I'm still having some trouble with this package.  After installing the 'typing' package through reticulate I am now getting this error which appears to be associated with the 'scipy' package.  I've made sure I installed that as well but I keep getting this error--

Error: package or namespace load failed for ‘pspm’:
 .onLoad failed in loadNamespace() for 'pspm', details:
  call: py_run_file_impl(file, local, convert)
  error: ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-39-x86_64-linux-gnu.so)
Run `reticulate::py_last_error()` for details.
Error: loading failed
Execution halted

**Comment by carl-mc** [comment]
From what I can see, this might be an ana/miniconda dependency issue (e..g [here](https://stackoverflow.com/questions/69993591/scipy-not-using-anacondas-local-lib-for-libgcc) ). Can you follow their solutions, e.g., by running

`conda install -c anaconda libstdcxx-ng`
or try 
`conda install -c miniconda libstdcxx-ng`
on the command line? 

On which OS are you working? Is there a chance that you can install Python3 and run reticulate through it (rather than through miniconda, since this may be causing some issues..)
